### ISSUE TITLE
navigation on http://learn-the-web.algonquindesign.ca doesn't seem to work anymore

### ISSUE THREAD

**Issue by bboydflo** [acgd-learn-the-web/topics#1]
I noticed that just over the weekend the navigation on the website won't work anymore...I am not sure if it is a jekyll problem or github issue. 

Really hope it will be fixed :) Thanks for the tutorials

**Comment by thomasjbradley** [comment]
Thanks! I just noticed that myself and am trying to debug it right now.

**Comment by thomasjbradley** [comment]
Seems to be fixed now. I don’t really know what happened, maybe a faulty Jekyll build or something.
