### ISSUE TITLE
Link to Hover video tutorial 404 error 

### ISSUE THREAD

**Issue by emnemdesign** [acgd-learn-the-web/topics#13]
To follow the hover setup lesson hyperlink leads to a 404 page also

**Comment by thomasjbradley** [comment]
Where is that link?

**Comment by emnemdesign** [comment]
It is under web dev 6, domains&dns under sub header buying a domain on hover
![2E7F1759-1973-417F-85CF-3555F5097200](https://user-images.githubusercontent.com/6352997/74598934-a982a400-5048-11ea-90cb-231aed74ae9a.png)
