### ISSUE TITLE
What about pagination? :)

### ISSUE THREAD

**Issue by arturogh** [acgd-learn-the-web/topics#3]
Hey,

Very helpful videos. Specially how to loop through post categories.

I'm having a hard time though generating the next/previous page links.

Found these:

https://github.com/midnightSuyama/jekyll-paginate-category
https://gist.github.com/Mingan/c635d8dd6b1bb0c10266/revisions

Would really appreciate your input / help :)

**Comment by thomasjbradley** [comment]
Have you checked out the Jekyll documentation on pagination? It seems pretty good:
https://jekyllrb.com/docs/pagination/

**Comment by arturogh** [comment]
I have. And it is good. But it doesn't support posts using categories 👎

**Comment by thomasjbradley** [comment]
Okay, I see.

That Jekyll Paginate Category plugin should work okay for you then.
But if you're hosting on GitHub Pages it will be more difficult to use.

I'd follow the “Or install yourself” instruction to get it set up.

**Comment by arturogh** [comment]
I did try that one, but couldn't get it to work :( I'm thinking my loop was wrong or something.

This is the loop I'm using FYI:

{% for blog in site.categories.blog %}
  {% if blog.category == 'blog' %}
  <article class="blog-post-item"><a href="{{site.baseurl}}{{ blog.url }}">
    <div class="blog-post-thumbnail" style="background: linear-gradient(0deg, rgba(0,0,0,0.70) 0%, rgba(0,0,0,0.0) 50%, rgba(0,0,0,0.50) 100%), url('{{site.baseurl}}/public/images/post-images/{{blog.image}}/thumbnail.jpg'); background-position: center center; background-size: cover">
      <div class="content">
        <div class="text">
          <h2>{{ blog.title }}</h2>
          <span>{{ blog.time }} min read</span>
        </div>
      </div>
    </div></a>
    <p>{{ blog.excerpt }}</p>
  </article>
  {% endif %}
{% endfor %}

**Comment by thomasjbradley** [comment]
It looks like maybe instead of looping over the `site.categories` you need to use the `paginator` loop here:
https://github.com/midnightSuyama/jekyll-paginate-category#indexhtml-category_layout
