### ISSUE TITLE
Error trying to parse settings

### ISSUE THREAD

**Issue by matthewpeixoto** [acgd-learn-the-web/topics#6]
Error after pasting and saving user settings in Sublime Text.

<img width="532" alt="screen shot 2016-08-28 at 10 41 45 pm" src="https://cloud.githubusercontent.com/assets/16690200/18039454/2f625a66-6d71-11e6-95a4-a52d3e8a69c9.png">

**Comment by thomasjbradley** [comment]
Try it again—it should be fixed now.
